apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: next-template
  title: Next Template
  description: Template for simple Next.js service
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
        - projectId
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        projectId:
          title: GCP Project ID
          type: string
          description: Your Google Cloud Project ID
        repoOwner:
          title: Repo Owner
          type: string
          description: Your Github Repository Owner

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
        copyWithoutTemplating:
          - '.github/workflows/pipeline.yml'

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: 'github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.name }}'
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}