apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: 'github.com/project-slug: ${{ values.repoOwner }}/${{ values.name }}'
spec:
  type: service
  owner: group:sre
  lifecycle: experimental