apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: 'rey-gdp-intern/test-next'
spec:
  type: service
  owner: group:sre
  lifecycle: experimental