name: 'Terraform CI'
on:
  workflow_dispatch:
    inputs:
      trigger_name:
        description: 'Name of the Cloud Build trigger'
        required: true
      project_id:
        description: 'GCP Project ID'
        required: true
      repo_name:
        description: 'Name of the repository'
        required: true
      repo_owner:
        description: 'Owner of the repository'
        required: true
      branch_name:
        description: 'Branch name to trigger the build'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          GCP_PROJECT_ID: ${{ github.event.inputs.project_id }}
          GCP_TRIGGER_NAME: ${{ github.event.inputs.trigger_name }}
          GCP_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GCP_REPO_OWNER: ${{ github.event.inputs.repo_owner }}
          GCP_BRANCH_NAME: ${{ github.event.inputs.branch_name }}
        run: terraform apply -auto-approve -var "project_id=${{ env.GCP_PROJECT_ID }}" -var "trigger_name=${{ env.GCP_TRIGGER_NAME }}" -var "repo_name=${{ env.GCP_REPO_NAME }}" -var "repo_owner=${{ env.GCP_REPO_OWNER }}" -var "branch_name=${{ env.GCP_BRANCH_NAME }}"
