apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: branch-deployment-template
  title: Branch Deployment
  description: Template for develop deployment v1.3
spec:
  owner: group:sre
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - repoOwner
        - repoName
        - sourceBranch
        - newBranch
      properties:
        repoOwner:
          title: Repo Owner
          type: string
          description: GitHub Repository Owner/Group
          enum:
            - rey-gdp-intern
        repoName:
          title: Repository Name
          type: string
          description: The name of the repository
        sourceBranch:
          title: Source Branch
          type: string
          enum:
            - master
            - staging
            - develop
        newBranchEnvironment:
          title: New Branch Environment
          type: string
          description: Environment of the new branch
          enum:
            - staging
            - develop
        newBranchName:
          title: New Branch Environment
          type: string
          description: Name of the new branch (e.g. "feat-1")

  steps:
    - id: create-branch
      name: Create GitHub Branch
      action: custom:github:branch:create
      input:
        repoOwner: ${{ parameters.repoOwner }}
        repoName: ${{ parameters.repoName }}
        sourceBranch: ${{ parameters.sourceBranch }}
        newBranch: ${{ parameters.newBranch }}

  output:
    links:
      - title: Repository
        url: 'github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}'
