apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: golang-template
  title: Golang template
  description: Template for golang with GCB v1.2
spec:
  owner: group:sre
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
        - repoOwner
        - projectId
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        repoOwner:
          title: Repo Owner
          type: string
          description: Github Repository Owner/Group
          enum:
            - rey-gdp-intern
        projectId:
          title: Project ID
          type: string
          description: GCP Project ID
          enum:
            - intern-infra
            - antrein-ta

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          repoOwner: ${{ parameters.repoOwner }}
          projectId: ${{ parameters.projectId }}
        copyWithoutTemplating:
          - '.github/workflows/pipeline.yml'

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: 'github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.name }}'
        repoVisibility: public

    - id: create-gcp-trigger
      name: Create GCP Trigger
      action: custom:gcp:cloudbuild:trigger:create
      input:
        projectId: ${{ parameters.projectId }}
        repoOwner: ${{ parameters.repoOwner }}
        repoName: ${{ parameters.name }}
        region: "asia-east1"

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
