apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcp-compute-engine-vm
  title: GCP Compute Engine VM Template
  description: Create new GCP Compute Engine via Terraform v1.2
  tags:
  - gcp
  - compute
  - terraform
spec:
  owner: group:sre
  type: resource

  parameters:
  - title: Fill in some steps
    required:
    - name
    properties:
      name:
        title: Name
        type: string
        pattern: '^[a-z-]+$' # Only lower letters and "-"
        description: Unique name for your Compute Engine VM
      repoOwner:
        title: Repo Owner
        type: string
        description: GitHub Repository Owner/Group
        enum:
          - rey-gdp-intern
      projectId:
        title: Project ID
        type: string
        description: GCP Project ID
        enum:
          - intern-infra
          - antrein-ta

  - title: Project Details
    required:
    - zone
    - machine_type
    - ssh_username
    - ssh_password
    properties:
      zone:
        title: GCP Zone
        type: string
      machine_type:
        title: Machine Type
        type: string
        default: e2-micro
      ssh_username:
        title: SSH Username
        type: string
      ssh_password:
        title: SSH Password
        type: string

  steps:
  - id: tf-template
    name: Create a Terraform file for GCP Compute Engine VM
    action: fetch:template
    input:
      url: ./content
      targetPath: ./outputs
      values:
        name: ${{ parameters.name }}
        resource_name: ${{ parameters.name }}
        machine_type: ${{ parameters.machine_type }}
        zone: ${{ parameters.zone }}
        ssh_username: ${{ parameters.ssh_username }}
        ssh_password: ${{ parameters.ssh_password }}
        repoOwner: ${{ parameters.repoOwner }}
        projectId: ${{ parameters.projectId }}

  - id: github_pr
    name: Create GitHub PR
    action: publish:github:pull-request
    input:
      repoUrl: 'github.com?owner=rey-gdp-intern&repo=terraform'
      targetBranchName: 'main'
      branchName: 'develop'
      title: 'Create ${{ parameters.name }} GCP Compute Engine VM'
      description: |
        ## Creating GCP Compute Engine VM
        
        This is an initial pull request to create a GCP Compute Engine VM and was created based on the Backstage template.

        *created by: Backstage
      sourcePath: ./outputs/compute-engine
      targetPath: 'resource/compute-engine/${{ parameters.name }}'

  - id: label_pr
    name: Add labels to PR
    action: github:issues:label
    input:
      repoUrl: 'github.com?owner=rey-gdp-intern&repo=terraform'
      number: '${{ steps.github_pr.output.pullRequestNumber }}'
      labels:
      - backstage-terraform

  output:
    links:
    - title: 'Go to pull request'
      url: ${{ steps.github_pr.output.remoteUrl }}
      icon: github
