apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-gcp-compute-engine-vm
  title: GCP Compute Engine VM Template
  description: Create new GCP Compute Engine via Terraform v1.2
  tags:
  - gcp
  - compute
  - terraform
spec:
  owner: group:sre
  type: resource

  parameters:
  - title: Fill in some steps
    required:
    - name
    properties:
      name:
        title: Name
        type: string
        pattern: '^[a-z0-9-_]+$' # Only lower letters, numbers, "-" and "_"
        description: Unique name for your Compute Engine VM
      repoOwner:
        title: Repo Owner
        type: string
        description: GitHub Repository Owner/Group
        enum:
          - rey-gdp-intern
      projectId:
        title: Project ID
        type: string
        description: GCP Project ID
        enum:
          - intern-infra
          - antrein-ta

  - title: Project Details
    required:
    - zone
    - machine_type
    - ssh_username
    - ssh_password
    properties:
      zone:
        title: GCP Zone
        type: string
        enum:
          - asia-southeast2-a
          - asia-southeast2-b
          - asia-southeast2-c

      machine_type:
        title: Machine Type
        type: string
        enum:
          - e2-micro
          - e2-small
          - e2-medium
      ssh_username:
        title: SSH Username
        type: string
      ssh_password:
        title: SSH Password
        type: string

  steps:
  - id: tf-template
    name: Create a Terraform file for GCP Compute Engine VM
    action: fetch:template
    input:
      url: ./content
      targetPath: ./outputs
      values:
        name: ${{ parameters.name }}
        resource_name: ${{ parameters.name }}
        machine_type: ${{ parameters.machine_type }}
        zone: ${{ parameters.zone }}
        ssh_username: ${{ parameters.ssh_username }}
        ssh_password: ${{ parameters.ssh_password }}
        repoOwner: ${{ parameters.repoOwner }}
        projectId: ${{ parameters.projectId }}
        gcp_credentials_path: ${{ parameters.projectId == 'antrein-ta' ? './../../../credentials/gcp_sa_antrein_ta.json' : './../../../credentials/gcp_sa_intern_infra.json' }}

  - id: github_pr
    name: Create GitHub PR
    action: publish:github:pull-request
    input:
      repoUrl: 'github.com?owner=rey-gdp-intern&repo=terraform'
      targetBranchName: 'main'
      branchName: 'compute-engine-${{ parameters.name }}'
      title: 'Create ${{ parameters.name }} GCP Compute Engine VM'
      description: 'Pull request for new google compute engine resource'
      sourcePath: ./outputs
      targetPath: 'resource/compute-engine/${{ parameters.name }}'

  - id: label_pr
    name: Add labels to PR
    action: github:issues:label
    input:
      repoUrl: 'github.com?owner=rey-gdp-intern&repo=terraform'
      number: '${{ steps.github_pr.output.pullRequestNumber }}'
      labels:
      - backstage-terraform

  - id: merge-branch
    name: Merge GitHub Branch
    action: custom:github:pr:merge
    input:
      repoOwner: rey-gdp-intern
      repoName: terraform
      sourceBranch: 'compute-engine-${{ parameters.name }}'

  - id: register
    name: Register
    action: catalog:register
    input:
      repoContentsUrl: 'https://github.com/rey-gdp-intern/terraform/tree/main/resource/compute-engine/${{ parameters.name }}'
      catalogInfoPath: '/resource/compute-engine/${{ parameters.name }}/catalog-info.yaml'

  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
