apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-templates
  description: A collection of all Organisasi Bawah Tanah project templates
spec:
  type: url
  targets:
    - ./golang/template.yaml