apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-templates
  description: A template
spec:
  targets:
    - ./golang/template.yaml
    - ./next/template.yaml
    - ./infra/github/branch/template.yaml
    - ./infra/cloud/VM/template.yaml